#!/usr/bin/env python

import os
import sys
import subprocess
import logging as log

class CmdError(Exception):
    pass

def main():
    log.basicConfig(format='%(levelname)s: %(message)s', level=log.INFO)
    if len(sys.argv[1:]) < 2:
        _usage()
        sys.exit(1)
    sources = sys.argv[1:-1]
    destination = sys.argv[-1]
    if len(sources) == 1:
        # We are unpacking a single file.
        source = sources[0]
        if _is_dir(destination):
            destination = os.path.join(destination, os.path.basename(source))
            if source.endswith('.lz4'):
                destination = destination[:-4]
        sources_destinations = [(source, destination)]
    else:
        destination_dir = destination
        if os.path.isfile(os.path.normpath(destination_dir)):
            _abort('{} exists and is not a directory'.format(os.path.normpath(destination_dir)))
        sources_destinations = []
        for source in sources:
            destination = os.path.join(destination_dir, os.path.basename(source))
            if source.endswith('.lz4'):
                destination = destination[:-4]
            sources_destinations.append((source, destination))
    for s, d in sources_destinations:
        _run_lz4(s, d)

# helper functions

def _usage():
    print "USAGE: lz4get SRC [SRC]... DEST"

def _is_dir(path):
    return path.endswith('/') or os.path.isdir(path)

def _is_existing_file(s):
    return not os.path.isdir(os.path.normpath(s))

def _is_not_dir(s):
    return (not _is_dir(s)) or _is_existing_file(s)

def _abort(msg, ret=1):
    log.error(os.path.basename(sys.argv[0]) + ': ' + msg.rstrip())
    sys.exit(ret)

def _run(cmd):
    if os.system(cmd) != 0:
        raise CmdError

def _run_lz4(src, dest):
    log.info('unpacking {} as {}'.format(src, dest))
    if os.path.isdir(src):
        _abort('{} is a directory'.format(src))
    if os.path.isfile(dest):
        overwriting = True
    else:
        overwriting = False
    output = subprocess.check_output(['lz4', '-d', '-f', src, dest], stderr=subprocess.STDOUT)
    if not 'Successfully' in output:
        log.error(output.rstrip())
        sys.exit(1)

if __name__ == '__main__':
    main()
