#!/usr/bin/env python

"""
  USAGE: partition [-s SEED] N i

  Split standard input rows into N nearly-equal sized groups and print i-th group.
  With -s option, randomize the input lines (set SEED argument for reproducible results).

  blazej.krzeminski@ecmwf.int, 2011

"""

import sys
import random
import getopt


def usage():
    sys.stderr.write("USAGE: partition [-s SEED] NGROUPS GROUP\n")




def partition(lst, n):
    division = len(lst) / float(n)
    return [ lst[int(round(division * i)): int(round(division * (i + 1)))] for i in xrange(n) ]




if __name__ == "__main__":


    argv = sys.argv[1:]
    seed = None

    try:
        opts, args = getopt.getopt(argv, "s:", "seed=")
    except getopt.GetoptError:
        usage()
        sys.exit(2)

    for opt, arg in opts:
        if opt == "-s":
            seed = int(arg)

    if len(args) <> 2:
        sys.stderr.write("partition: 2 arguments expected\n")
        usage()
        sys.exit(2)

    nparts = int(args[0])
    part = int(args[1])

    if part > nparts:
        sys.stderr.write("partition: expected GROUP <= NGROUPS\n")
        usage()
        sys.exit(2)

    if nparts < 1 or part < 1:
        print "partition: arguments must be greater than 0"
        usage()
        sys.exit(2)

    lines = sys.stdin.readlines()
    if (seed):
        random.seed(seed)
        random.shuffle(lines)

    for line in partition(lines, nparts)[part - 1]:
        print line.rstrip('\r\n')
